admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /


core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
